# Generated by Django 4.2.4 on 2023-10-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iexcel_Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='date')),
                ('title', models.CharField(max_length=120)),
                ('extract', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
