# Generated by Django 4.2.4 on 2023-10-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iexcel_blog',
            name='content',
            field=models.TextField(max_length=1024),
        ),
    ]
