# Generated by Django 4.2.4 on 2023-10-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_iexcel_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iexcel_blog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='iexcel_blog',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
