# Generated by Django 4.2.4 on 2023-10-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_iexcel_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iexcel_blog',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
